-- ==============================================================================
-- MIGRASI: Tabel Login untuk Supabase
-- Jalankan di Supabase SQL Editor: https://app.supabase.com
-- Paste ke SQL Editor > Run
-- ==============================================================================

-- 1. BUAT TABEL LOGIN (kalau belum ada)
CREATE TABLE IF NOT EXISTS public.login (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member', 'guest')),
    tier VARCHAR(50) DEFAULT 'Regular',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. INDEX UNTUK QUERY LOGIN
CREATE INDEX IF NOT EXISTS idx_login_username ON public.login(username);
CREATE INDEX IF NOT EXISTS idx_login_role ON public.login(role);

-- 3. INSERT DATA DEMO (admin & member)
INSERT INTO public.login (username, password, role, tier)
VALUES 
    ('admin', '123', 'admin', NULL),
    ('member', '123', 'member', 'Gold')
ON CONFLICT (username) DO NOTHING;

-- 4. ENABLE RLS (opsional — disable kalau masih development)
ALTER TABLE public.login ENABLE ROW LEVEL SECURITY;

-- 5. RLS POLICY: allow all operations (anon key)
-- Gunakan ini untuk development. Nanti bisa diperketat.
CREATE POLICY "Allow all for anon" ON public.login
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- 6. GRANT PERMISSIONS
GRANT ALL ON public.login TO anon, authenticated;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- ==============================================================================
-- VERIFIKASI: Cek data sudah masuk
-- ==============================================================================
SELECT * FROM public.login;
